### ISSUE TITLE
Scrapper login

### ISSUE THREAD

**Issue by SouSingh** [ai16z/eliza#1066]
Error: {"errors":[{"code":399,"message":"Incorrect. Please try again. g;173416064338586466:-1734160643646:ccVhgNQFewzfeK9cjAREzndr:8"}]}
    at TwitterUserAuth.executeFlowTask (file:///Users/kushagra/go/src/gihub.com/Cartman/Eliza-wraper/node_modules/.pnpm/agent-twitter-client@0.0.13/node_modules/agent-twitter-client/dist/node/esm/index.mjs:552:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async TwitterUserAuth.handleAcid (file:///Users/kushagra/go/src/gihub.com/Cartman/Eliza-wraper/node_modules/.pnpm/agent-twitter-client@0.0.13/node_modules/agent-twitter-client/dist/node/esm/index.mjs:508:12)
    at async TwitterUserAuth.login (file:///Users/kushagra/go/src/gihub.com/Cartman/Eliza-wraper/node_modules/.pnpm/agent-twitter-client@0.0.13/node_modules/agent-twitter-client/dist/node/esm/index.mjs:347:16)
    at async Scraper.login (file:///Users/kushagra/go/src/gihub.com/Cartman/Eliza-wraper/node_modules/.pnpm/agent-twitter-client@0.0.13/node_modules/agent-twitter-client/dist/node/esm/index.mjs:2280:5)
    at async ClientBase.init (file:///Users/kushagra/go/src/gihub.com/Cartman/Eliza-wraper/node_modules/.pnpm/@ai16z+client-twitter@0.1.4-alpha.3@google-cloud+vertexai@1.9.2_@langchain+core@0.3.23_opena_p7je7bhkaswxwoghczkrgshcom/node_modules/@ai16z/client-twitter/dist/index.js:1015:7)
    at async Object.start (file:///Users/kushagra/go/src/gihub.com/Cartman/Eliza-wraper/node_modules/.pnpm/@ai16z+client-twitter@0.1.4-alpha.3_@google-cloud+vertexai@1.9.2_@langchain+core@0.3.23_opena_p7je7bhkaswxwoghczkrgshcom/node_modules/@ai16z/client-twitter/dist/index.js:1377:5)
    at async initializeClients (file:///Users/kushagra/go/src/gihub.com/Cartman/Eliza-wraper/src/index.ts:156:32)
    at async startAgent (file:///Users/kushagra/go/src/gihub.com/Cartman/Eliza-wraper/src/index.ts:212:25)
    at async startAgents (file:///Users/kushagra/go/src/gihub.com/Cartman/Eliza-wraper/src/index.ts:309:13)
 ⛔ ERRORS
   Error starting agents:
   {}
   
   whenever I try to do login or re run again through it got me that same error

**Comment by lalalune** [comment]
You might need to remove your db.sqlite (there are better ways to do this but that's probably it)
You could have your env vars wrong.
I don't think this is a bug, probably bad config or bad cookies in your cache

**Comment by s29papi** [comment]
@lalalune facing the same issue and i've deleted db.sqlite and also rebuilt. configuration params are also correct and it errors same "Error: {"errors":[{"code":399,"message":"Incorrect. Please try again. g;173461914653681618:-1734619146851:NtaLTgbbm1DcTi0FISafmEa3:8"}]}..."
