### ISSUE TITLE
Node 23 Support issue with better-sqlite3

### ISSUE THREAD

**Issue by lalalune** [ai16z/eliza#167]
**Describe the bug**

```
Error: The module '/root/ruby/node_modules/.pnpm/better-sqlite3@11.5.0/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 127. This version of Node.js requires
NODE_MODULE_VERSION 131. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object..node (node:internal/modules/cjs/loader:1735:18)
    at Module.load (node:internal/modules/cjs/loader:1315:32)
    at Function._load (node:internal/modules/cjs/loader:1125:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:216:24)
    at Module.require (node:internal/modules/cjs/loader:1337:12)
    at require (node:internal/modules/helpers:139:16)
    at bindings (/root/ruby/node_modules/.pnpm/bindings@1.5.0/node_modules/bindings/bindings.js:112:48)
    at new Database (/root/ruby/node_modules/.pnpm/better-sqlite3@11.5.0/node_modules/better-sqlite3/lib/database.js:48:64)
    at initializeDatabase (file:///root/ruby/core/src/cli/index.ts:92:50) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v23.1.0
```
**To Reproduce**

Run it with Node 23

**Expected behavior**

Just works

**Comment by bembengcs** [comment]
solve by running this command 

> `pnpm rebuild better-sqlite3 `

**Comment by lalalune** [comment]
> pnpm rebuild better-sqlite3

nice
