### ISSUE TITLE
build docs doesn't seem to be working

### ISSUE THREAD

**Issue by yodamaster726** [ai16z/eliza#176]
**Trying to build the docs from what I saw was being incorporated the other night and it's erroring out**

First it errors out saying it wants node 23.1 but the project is using 22.xx.  I update to 23.1 using nvm and it still errors out.

Putting this here as a place holder - this needs more work.

eliza>$ pnpm build-docs

> eliza@ build-docs /Users/davidjaramillo/Documents/Projects/eliza
> pnpm --dir docs build

 WARN  Unsupported engine: wanted: {"node":"23.1.0"} (current: {"node":"v22.11.0","pnpm":"9.12.3"})

> eliza-docs@0.0.0 build /Users/davidjaramillo/Documents/Projects/eliza/docs
> docusaurus build

[INFO] [en] Creating an optimized production build...
[info] Loaded plugin typedoc-plugin-markdown
[error] The tsconfig file /Users/davidjaramillo/Documents/Projects/eliza/tsconfig.json does not exist

[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (/Users/davidjaramillo/Documents/Projects/eliza/node_modules/.pnpm/@docusaurus+core@3.5.2_@docusaurus+types@3.5.2_acorn@8.14.0_react-dom@18.2.0_react@18.2.0__re_e6f3ssmiin2uov5e54dllhgixm/node_modules/@docusaurus/core/lib/commands/build.js:54:19)
    at async /Users/davidjaramillo/Documents/Projects/eliza/node_modules/.pnpm/@docusaurus+core@3.5.2_@docusaurus+types@3.5.2_acorn@8.14.0_react-dom@18.2.0_react@18.2.0__re_e6f3ssmiin2uov5e54dllhgixm/node_modules/@docusaurus/core/lib/commands/build.js:65:9
    at async mapAsyncSequential (/Users/davidjaramillo/Documents/Projects/eliza/node_modules/.pnpm/@docusaurus+utils@3.5.2_@docusaurus+types@3.5.2_acorn@8.14.0_react-dom@18.2.0_react@18.2.0__r_ommau7el7tbopkaz2g33fzjgfi/node_modules/@docusaurus/utils/lib/jsUtils.js:21:24)
    at async Command.build (/Users/davidjaramillo/Documents/Projects/eliza/node_modules/.pnpm/@docusaurus+core@3.5.2_@docusaurus+types@3.5.2_acorn@8.14.0_react-dom@18.2.0_react@18.2.0__re_e6f3ssmiin2uov5e54dllhgixm/node_modules/@docusaurus/core/lib/commands/build.js:63:5) {
  [cause]: Error: ENOENT: no such file or directory, scandir '/Users/davidjaramillo/Documents/Projects/eliza/src'
      at Object.readdirSync (node:fs:1502:26)
      at glob (/Users/davidjaramillo/Documents/Projects/eliza/node_modules/.pnpm/typedoc@0.26.11_typescript@5.6.3/node_modules/typedoc/dist/lib/utils/fs.js:259:32)
      at /Users/davidjaramillo/Documents/Projects/eliza/node_modules/.pnpm/typedoc@0.26.11_typescript@5.6.3/node_modules/typedoc/dist/lib/utils/entry-point.js:207:38
      at Array.flatMap (<anonymous>)
      at expandGlobs (/Users/davidjaramillo/Documents/Projects/eliza/node_modules/.pnpm/typedoc@0.26.11_typescript@5.6.3/node_modules/typedoc/dist/lib/utils/entry-point.js:206:31)
      at getEntryPoints (/Users/davidjaramillo/Documents/Projects/eliza/node_modules/.pnpm/typedoc@0.26.11_typescript@5.6.3/node_modules/typedoc/dist/lib/utils/entry-point.js:83:53)
      at _classThis.getEntryPoints (/Users/davidjaramillo/Documents/Projects/eliza/node_modules/.pnpm/typedoc@0.26.11_typescript@5.6.3/node_modules/typedoc/dist/lib/application.js:299:53)
      at _classThis.convert (/Users/davidjaramillo/Documents/Projects/eliza/node_modules/.pnpm/typedoc@0.26.11_typescript@5.6.3/node_modules/typedoc/dist/lib/application.js:321:38)
      at generateTypedoc (/Users/davidjaramillo/Documents/Projects/eliza/node_modules/.pnpm/docusaurus-plugin-typedoc@1.0.5_typedoc-plugin-markdown@4.2.9_typedoc@0.26.11_typescript@5.6.3__/node_modules/docusaurus-plugin-typedoc/dist/plugin.js:99:31)
      at async Object.pluginDocusaurus [as plugin] (/Users/davidjaramillo/Documents/Projects/eliza/node_modules/.pnpm/docusaurus-plugin-typedoc@1.0.5_typedoc-plugin-markdown@4.2.9_typedoc@0.26.11_typescript@5.6.3__/node_modules/docusaurus-plugin-typedoc/dist/plugin.js:40:9) {
    errno: -2,
    code: 'ENOENT',
    syscall: 'scandir',
    path: '/Users/davidjaramillo/Documents/Projects/eliza/src'
  }
}
[INFO] Docusaurus version: 3.5.2
Node version: v22.11.0
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
eliza>$

**Comment by lalalune** [comment]
Fixed, other issues but this one is gud
