### ISSUE TITLE
sqlite_vss unsupported on win32-x64

### ISSUE THREAD

**Issue by sirkitree** [ai16z/eliza#37]
recieving error:

```
Server running at http://localhost:3000/
file:///C:/Users/sirki/repos/eliza/src/adapters/sqlite/sqlite_vss.ts:31
        throw new Error(`Unsupported platform for sqlite-vss, on a ${platform}-${arch} machine, but not in supported platforms (${supportedPlatforms
              ^

Error: Unsupported platform for sqlite-vss, on a win32-x64 machine, but not in supported platforms (darwin-x64,darwin-arm64,linux-x64). Consult the sqlite-vss NPM package README for details.
    at loadablePathResolver (file:///C:/Users/sirki/repos/eliza/src/adapters/sqlite/sqlite_vss.ts:31:15)
    at getVectorLoadablePath (file:///C:/Users/sirki/repos/eliza/src/adapters/sqlite/sqlite_vss.ts:43:12)
    at loadVector (file:///C:/Users/sirki/repos/eliza/src/adapters/sqlite/sqlite_vss.ts:50:22)
    at load (file:///C:/Users/sirki/repos/eliza/src/adapters/sqlite/sqlite_vss.ts:56:5)
    at new SqliteDatabaseAdapter (file:///C:/Users/sirki/repos/eliza/src/adapters/sqlite.ts:38:9)
    at startAgent (file:///C:/Users/sirki/repos/eliza/src/index.ts:68:16)
    at startAgents (file:///C:/Users/sirki/repos/eliza/src/index.ts:181:15)
    at file:///C:/Users/sirki/repos/eliza/src/index.ts:184:1

Node.js v20.18.0
```

I gather that sqlite_vss isn't' compatible with win32 and i'd like to run this on my windoze machine. I think I saw mention of using postgres in chat, perhaps that'd fix this.

**Comment by wanderin** [comment]
getting the same issue. Should we explore alternatives, or should we just use linux

**Comment by wanderin** [comment]
@sirkitree did you ever figure this out?

**Comment by sirkitree** [comment]
No i just started developing on osx for now. I think the solution is swapping out sqlite_vss for something else entirely. Postgres was metnioned in a chat somewhere

**Comment by sirkitree** [comment]
from dev chat:

> we have a postgres adapter with pgvector
> we just need to switch to that
> if you see, we are using SqliteDatabaseDadapter
> But we have a PostgresDatabaseAdapter
> works gud

https://github.com/asg017/sqlite-vss/issues/98#issuecomment-2002641515
