### ISSUE TITLE
TypeError while generating a message response

### ISSUE THREAD

**Issue by vvisigoth** [ai16z/eliza#657]
**Describe the bug**

Receive the following error when trying to chat after first boot:

(I put a printf before the error to try to see why it's throwing the error)

```

You: Hello
Response {
  status: 405,
  statusText: 'Method Not Allowed',
  headers: Headers {
    date: 'Thu, 28 Nov 2024 21:56:32 GMT',
    server: 'uvicorn',
    'content-length': '31',
    'content-type': 'application/json',
    'x-process-time': '0'
  },
  body: ReadableStream { locked: false, state: 'readable', supportsBYOB: true },
  bodyUsed: false,
  ok: false,
  redirected: false,
  type: 'basic',
  url: 'http://localhost:3000/trump/message'
}
Error fetching response: TypeError: data.forEach is not a function
    at handleUserInput (file:///Users/redacted/se01/eliza/agent/src/index.ts:274:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async file:///Users/redacted/se01/eliza/agent/src/index.ts:234:13
```

**To Reproduce**

Happens after first chat message after first boot.

**Expected behavior**

Eliza produces a coherent response to the prompt.

**Additional context**

This is on `v0.1.4-alpha3`, macOS, node v23.3

I've tried this with an openai key and a xai key (trying to figure out if it was an API issue on that side) and the same error happens with both.

**Comment by vvisigoth** [comment]
This was a problem on my box. Can someone close/delete?
