### ISSUE TITLE
Twitter login some function not work. 

### ISSUE THREAD

**Issue by leonzijun** [ai16z/eliza#857]
["◎ Twitter client started"]

 ["◎ Waiting for Twitter login"]

 ⛔ ERRORS
   Error starting agent for character joi:
   {}

Error: {"errors":[{"code":399,"message":"Incorrect. Please try again."}]}
    at TwitterUserAuth.executeFlowTask (file:///home/eliza/node_modules/agent-twitter-client/dist/node/esm/index.mjs:569:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async TwitterUserAuth.handleEnterAlternateIdentifierSubtask (file:///home/eliza/node_modules/agent-twitter-client/dist/node/esm/index.mjs:439:12)
    at async TwitterUserAuth.login (file:///home/eliza/node_modules/agent-twitter-client/dist/node/esm/index.mjs:344:16)
    at async Scraper.login (file:///home/eliza/node_modules/agent-twitter-client/dist/node/esm/index.mjs:2914:5)
    at async _ClientBase.init (file:///home/eliza/packages/client-twitter/dist/index.js:847:13)
    at async Object.start (file:///home/eliza/packages/client-twitter/dist/index.js:1097:9)
    at async initializeClients (file:///home/eliza/agent/src/index.ts:217:32)
    at async startAgent (file:///home/eliza/agent/src/index.ts:308:25)
    at async startAgents (file:///home/eliza/agent/src/index.ts:331:13)
 ⛔ ERRORS
   Error starting agents:
   {}

**Comment by mohammadrz003** [comment]
how did you solve this issue?
