### ISSUE TITLE
Error pnpm start - Promise.withResolvers(): pdfjs-dist

### ISSUE THREAD

**Issue by 0xMxxx** [ai16z/eliza#902]
**Describe the bug**

Doing all steps for the quick start, once pnpm start comes you get this error:

TypeError: Cannot read properties of undefined (reading 'start')
    at Object.start (file:///home/x/Desktop/x/eliza/packages/client-twitter/dist/index.js:563:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async initializeClients (file:///home/x/Desktop/x/eliza/agent/src/index.ts:216:32)
    at async startAgent (file:///home/x/Desktop/x/eliza/agent/src/index.ts:306:25)
    at async startAgents (file:///home/x/Desktop/x/eliza/agent/src/index.ts:329:13)

**To Reproduce**

Doing all steps for the quick start, once pnpm start comes you get this error

**Additional context**

Using Bedian 12 - Tested on Windows Server and MacOs, all same error.
Clean download/ git clone and pretty straight forward error/bug.

------
NEXT steps: to follow ->
https://github.com/ai16z/eliza/issues/76
https://github.com/wojtekmaj/react-pdf/issues/1811

I'll come back to update.

**Comment by 0xMxxx** [comment]
tbh just redownloaded the project in a Debian 12, pnpm i - pnpm build and worked.
just randomly.
