### ISSUE TITLE
Twitter Search Client Broken

### ISSUE THREAD

**Issue by owenwahlgren** [ai16z/eliza#943]
**Describe the bug**
The `TwitterSearchClient` comes broken out of box
```bash
Error engaging with search terms: TypeError: Cannot read properties of undefined (reading 'id')
    at TwitterSearchClient.fetchHomeTimeline (file:///Users/owen.wahlgren/code/eliza/packages/client-twitter/dist/index.js:337:82)
    at TwitterSearchClient.engageWithSearchTerms (file:///Users/owen.wahlgren/code/eliza/packages/client-twitter/dist/index.js:812:45)
 ```

**To Reproduce**
Clone most recent release
Build `character.json` with `twitter` in character files `clients` array.
```json
 "clients": [
    "twitter",
    "telegram"
  ],
```

Update `packages/client-twitter/src/index.ts` to include search functionality
```bash
import { TwitterPostClient } from "./post.ts";
import { TwitterSearchClient } from "./search.ts";
import { TwitterInteractionClient } from "./interactions.ts";
import { IAgentRuntime, Client, elizaLogger } from "@ai16z/eliza";
import { validateTwitterConfig } from "./environment.ts";
import { ClientBase } from "./base.ts";

class TwitterManager {
    client: ClientBase;
    post: TwitterPostClient;
    search: TwitterSearchClient;
    interaction: TwitterInteractionClient;
    constructor(runtime: IAgentRuntime) {
        this.client = new ClientBase(runtime);
        this.post = new TwitterPostClient(this.client, runtime);
        this.search = new TwitterSearchClient(runtime); // don't start the search client by default (ADDED THIS)
        // this searches topics from character file, but kind of violates consent of random users
        // burns your rate limit and can get your account banned
        // use at your own risk
        this.interaction = new TwitterInteractionClient(this.client, runtime);
    }
}

export const TwitterClientInterface: Client = {
    async start(runtime: IAgentRuntime) {
        await validateTwitterConfig(runtime);

        elizaLogger.log("Twitter client started");

        const manager = new TwitterManager(runtime);

        await manager.client.init();

        await manager.post.start();

        await manager.interaction.start();

        await manager.search.onReady(); // (ADDED THIS)

        return manager;
    },
    async stop(_runtime: IAgentRuntime) {
        elizaLogger.warn("Twitter client does not support stopping yet");
    },
};

export default TwitterClientInterface;
```
Build and start project:

```bash
pnpm build
```
```bash
pnpm start
```

**Expected behavior**

Should engage in searched timeline activity outside of just mentions

**Comment by DaggerWilson** [comment]
I also received "runtime.getSetting is not defined" when uncommenting and adding onReady to start the client on startup  and uncommenting

Tried fixing by updating createAgent and AgentRuntime, but ended up breaking the entire thing and won't launch.

**Comment by owenwahlgren** [comment]
> I also received "runtime.getSetting is not defined" when uncommenting and adding onReady to start the client on startup and uncommenting
> 
> Tried fixing by updating createAgent and AgentRuntime, but ended up breaking the entire thing and won't launch.

I resolved this in `packages/client-twitter/src/search.ts`

```javascript
 constructor(runtime: IAgentRuntime) {
        // Initialize the client and pass an optional callback to be called when the client is ready
        super(
            runtime, // change this
        );
    }
```

**Comment by owenwahlgren** [comment]
tbh this may be resolved if you bump to latest version of https://github.com/ai16z/agent-twitter-client

testing now

**Comment by DaggerWilson** [comment]
You've helped me overcome that roadblock, much appreciated! Now I see the search, but hitting:

```
Error engaging with search terms: TypeError: Cannot read properties of undefined (reading 'id')
    at TwitterSearchClient.fetchHomeTimeline (file:///root/eliza/packages/client-twitter/dist/index.js:311:82)
    at TwitterSearchClient.engageWithSearchTerms (file:///root/eliza/packages/client-twitter/dist/index.js:563:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

Possibly unrelated to this, but will keep testing

**Comment by owenwahlgren** [comment]
here is my initial fix:
https://github.com/ai16z/eliza/commit/d0d062b46de7d639e5ec6d165ae5f2bd37f0b201
this will twitter search `topics` in `character.json` and reply to one on eliza's startup,
I don't think it is properly looping though, still working on it.

if I make substantial progress maybe we can make a PR

**Comment by owenwahlgren** [comment]
PR here:
https://github.com/ai16z/eliza/pull/951

make sure you have `model` set in `character.json`

```bash
"modelProvider": "openai",
  "settings": {
    "temperature": 0.6,
    "secrets": {},
    "voice": {
      "model": "en_US-hfc_male-medium"
    },
    "model": "medium"
  },
 ```

**Comment by owenwahlgren** [comment]
resolved by https://github.com/ai16z/eliza/commit/649946c0e375e89ab64de55e69bb37a224f0fa50
