### ISSUE TITLE
TypeError - LinkedIn constructor error

### ISSUE THREAD

**Issue by Prem95** [ai16z/eliza#990]
**Describe the bug**

When integrating `client-linkedin`, an error occurs: "TypeError: linkedin_api_1.Client is not a constructor". This error prevents the LinkedIn client from starting properly.

**To Reproduce**

1. Attempt to start the LinkedIn client.
2. Observe the error message in the console.

**Expected behavior**

The LinkedIn client should start without any errors, and it should initialize the agent for the character NEEToshi successfully.

**Errors Log**

```
["◎ LinkedIn client started"]

⛔ ERRORS
Error starting agent for character NEEToshi:
{}

TypeError: linkedin_api_1.Client is not a constructor
at new ClientBase (/Users/prem/Documents/PERSONAL/eliza/packages/client-linkedin/dist/base.js:67:35)
at new LinkedInManager (/Users/prem/Documents/PERSONAL/eliza/packages/client-linkedin/dist/index.js:11:23)
at Object.start (/Users/prem/Documents/PERSONAL/eliza/packages/client-linkedin/dist/index.js:20:25)
at async initializeClients (file:///Users/prem/Documents/PERSONAL/eliza/agent/src/index.ts:232:33)
at async startAgent (file:///Users/prem/Documents/PERSONAL/eliza/agent/src/index.ts:349:25)
at async startAgents (file:///Users/prem/Documents/PERSONAL/eliza/agent/src/index.ts:372:13)

⛔ ERRORS
Error starting agents:
{}
```

*Additional context**

This issue may be related to the incorrect instantiation of the LinkedIn client due to `linkedin_api_1.Client` not being a constructor. Further investigation into the client library is needed.

**Comment by Prem95** [comment]
@bkellgren Are you sure ```linkedin-api: ^1.0.0``` is the correct package?

Reference - https://www.npmjs.com/package/linkedin-api?activeTab=readme

**Comment by Prem95** [comment]
Thanks for closing this. client-linkedin was trash

**Comment by yohairosen** [comment]
@lalalune thanks for this great project!

Where is the client-linkedin now? was it removed from the codebase?
Can't find on main or develop
